#!/bin/bash
mkdir "../bin/linux/"
mkdir "../bin/linux/e2k"

echo -e "Compile Coremark\n"

cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v3_O2 -O2 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v3_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v3_O3 -O3 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v3_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v3_O4 -O4 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v3_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_O2 -O2 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2_elbrus-8c -O2 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2_elbrus-1c+ -O2 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O2_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_O3 -O3 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3_elbrus-8c -O3 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3_elbrus-1c+ -O3 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O3_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_O4 -O4 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4_elbrus-8c -O4 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4_elbrus-1c+ -O4 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v4_ffast_O4_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_O2 -O2 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O2_elbrus-8c2 -O2 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O2_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_O3 -O3 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O3_elbrus-8c2 -O3 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O3_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_O4 -O4 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1  -lrt"\" -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O4_elbrus-8c2 -O4 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_e2k-elbrus-v5_ffast_O4_elbrus-8c2

echo -e "Compile Coremark 2 Thread\n"

cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O2 -O2 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O3 -O3 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O4 -O4 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v3_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O2 -O2 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2_elbrus-8c -O2 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2_elbrus-1c+ -O2 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O2_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O3 -O3 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3_elbrus-8c -O3 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3_elbrus-1c+ -O3 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O3_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O4 -O4 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4_elbrus-8c -O4 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4_elbrus-1c+ -O4 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v4_ffast_O4_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O2 -O2 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O2_elbrus-8c2 -O2 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O2_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O3 -O3 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O3_elbrus-8c2 -O3 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O3_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O4 -O4 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=2 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O4_elbrus-8c2 -O4 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp2_e2k-elbrus-v5_ffast_O4_elbrus-8c2

echo -e "Compile Coremark 4 Thread\n"

cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O2 -O2 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O3 -O3 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O4 -O4 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v3_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O2 -O2 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2_elbrus-8c -O2 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2_elbrus-1c+ -O2 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O2_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O3 -O3 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3_elbrus-8c -O3 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3_elbrus-1c+ -O3 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O3_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O4 -O4 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4_elbrus-8c -O4 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4_elbrus-1c+ -O4 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v4_ffast_O4_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O2 -O2 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O2_elbrus-8c2 -O2 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O2_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O3 -O3 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O3_elbrus-8c2 -O3 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O3_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O4 -O4 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=4 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O4_elbrus-8c2 -O4 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp4_e2k-elbrus-v5_ffast_O4_elbrus-8c2

echo -e "Compile Coremark 8 Thread\n"

cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O2 -O2 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O3 -O3 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O4 -O4 -march=elbrus-v3 -D options="\"e2k elbrus-v3 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v3_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O2 -O2 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2_elbrus-8c -O2 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2_elbrus-1c+ -O2 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O2_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O3 -O3 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3_elbrus-8c -O3 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3_elbrus-1c+ -O3 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O3_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O4 -O4 -march=elbrus-v4 -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4_elbrus-8c -O4 -mtune=elbrus-8c -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4_elbrus-8c
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4_elbrus-1c+ -O4 -mtune=elbrus-1c+ -ffast -fwhole -D options="\"e2k elbrus-v4 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v4_ffast_O4_elbrus-1c+
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O2 -O2 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O2 -O2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O2_elbrus-8c2 -O2 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O2_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O3 -O3 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O3 -O3 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O3
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O3_elbrus-8c2 -O3 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O3_elbrus-8c2
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O4 -O4 -march=elbrus-v5 -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O4 -O4 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O4
cc -Icoremark/linux64 -Icoremark -DFLAGS_STR=\""-g -DPERFORMANCE_RUN=1 -lrt"\" -DMULTITHREAD=8 -DUSE_FORK=1  -lrt coremark/core_list_join.c coremark/core_main.c coremark/core_matrix.c coremark/core_state.c coremark/core_util.c coremark/linux64/core_portme.c -o ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O4_elbrus-8c2 -O4 -mtune=elbrus-8c2 -ffast -fwhole -D options="\"e2k elbrus-v5 optimized\""
chmod +x ../bin/linux/e2k/coremark_mp8_e2k-elbrus-v5_ffast_O4_elbrus-8c2


